[project]
name = "transactions-service"
version = "0.1.0"
description = "Transactions Service for Event-Driven Portfolio Platform"
requires-python = ">=3.11"

dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "sqlmodel",
  "psycopg2-binary",
  "python-dotenv"
]

[tool.uvicorn]
factory = false
